import json
import re
import os

with open("insectss_fixed_v2_content.txt", "r", encoding="utf-8") as f:
    text = f.read()

# This text has line numbers, we need to strip them
text = re.sub(r"^\d+: ", "", text, flags=re.MULTILINE)

# It seems the text format is somewhat loose. Let's look at it manually and write the XML string directly in Python.

# English Data
en_data = {
    "crambidae": {
        "name": "Stem Borers / Moths (Aksip / Kuwong)",
        "general_desc": "Stem borers are among the most economically damaging pests in Philippine rice agriculture. The adult moths lay egg masses on rice leaves, and upon hatching, the larvae bore directly into the stem. In young plants, this kills the central shoot, a condition called “deadheart,” where the leaf turns yellow and can be easily pulled out. In mature plants, larval feeding at the stem base severs the connection to developing grains, producing bleached, empty panicles called “whitehead.” Several species attack rice, including the striped stem borer (Chilo suppressalis) and the yellow stem borer (Scirpophaga incertulas). Infestations are worst during the early vegetative and late booting stages. Losses can reach 30–50% of yield if left unmanaged.",
        "lifecycle": "Egg Mass: Females lay flat, scale-like egg masses of 50–150 eggs on the upper surface of rice leaves, usually near the midrib; eggs hatch in 5–7 days. Larva (inside stem): Newly hatched larvae immediately bore into the stem and feed internally; they pass through 5–6 instars over 20–30 days, causing deadheart in young plants or whitehead in mature ones. Pupa (inside stem): Pupation occurs inside the dead stem or tiller; this resting stage lasts 7–10 days. Adult Moth: Adults emerge, live for only 5–7 days, and mate immediately; females begin laying egg masses within days. Total cycle: 30–40 days.",
        "cultural": "• Synchronous planting across the community to break the pest cycle.\n• Harvesting crops at ground level to remove overwintering pupae.\n• Plowing and flooding fields immediately after harvest.",
        "bio_controls": "• Conserving and releasing parasitic wasps (e.g., Trichogramma) that destroy pest eggs.\n• Protecting natural predators like spiders and ground beetles.",
        "chemical": "• Applying systemic insecticides (e.g., Cartap hydrochloride) only if \"deadheart\" damage exceeds the 10% economic threshold during the vegetative stage."
    },
    "noctuidae": {
        "name": "Armyworms (Uod militar / Harabas)",
        "general_desc": "Armyworms (Mythimna separata and related species) are highly destructive caterpillars in the family Noctuidae that are notorious for mass-feeding events. Their name comes from their behavior of moving in large groups across fields like marching armies when food is scarce. Newly hatched larvae feed on the margins of leaves, but older instars (especially the 5th and 6th) consume entire leaves and even the panicle. A single larva can destroy several tillers in its lifetime. They tend to feed at night and hide in the soil during the day, making detection difficult. Outbreaks are common after prolonged dry spells followed by rain, and in the Philippines they pose a serious threat during the wet season. Severe infestations can strip entire paddies in a matter of days.",
        "lifecycle": "Egg: Females lay eggs in clusters of 100–300 on leaf surfaces; eggs hatch in 4–6 days. Larva (6 instars): Early instars feed on leaf margins; later instars (5th and 6th) consume entire leaves and panicles—feeding at night and hiding in the soil during the day; larval stage lasts 14–21 days. Pupa (soil): Larvae burrow into the soil to pupate; the pupal stage lasts 8–10 days. Adult Moth: Adults emerge, feed on nectar, and reproduce rapidly. Total cycle: ~30 days.",
        "cultural": "• Flooding seedbeds to drown caterpillars.\n• Deep plowing fields after harvest to expose soil-dwelling pupae to the sun.\n• Digging trenches around uninfected fields to prevent marching larvae from entering.",
        "bio_controls": "• Utilizing naturally occurring Nucleopolyhedrovirus (NPV) which specifically infects armyworm larvae.\n• Encouraging predatory birds and natural wasps.",
        "chemical": "• Spraying foliar insecticides (like synthetic pyrethroids) preferably in the late afternoon when larvae actively feed, but only during severe outbreaks."
    },
    "delphacidae": {
        "name": "Planthoppers (Ngusong kabayo - Brown)",
        "general_desc": "Planthoppers, particularly the Brown Planthopper (Nilaparvata lugens), are one of the most serious insect pests of rice in Asia. Both nymphs and adults feed by inserting their needle-like mouthparts into the phloem tissue at the base of the stem to extract sap. Heavy feeding causes “hopperburn,” a condition where infested areas of the field suddenly turn orange and dry up. Beyond direct damage, planthoppers also serve as vectors for Grassy Stunt and Ragged Stunt viruses, which can devastate entire crops. They reproduce rapidly under warm, humid, and nitrogen-rich canopy conditions, and certain biotypes have developed resistance to commonly used insecticides. In the Philippines, they are a leading cause of widespread crop losses, often triggered by the resurgence of populations after broad-spectrum pesticide use eliminates their natural predators.",
        "lifecycle": "Egg (leaf sheath): Females insert rows of eggs into the tissue of the leaf sheath, close to the waterline; eggs hatch in 7–10 days. Nymph (5 instars): Nymphs are active from the moment they hatch and begin feeding on phloem sap immediately; each instar lasts 2–4 days for a total of 15–20 days; early instars are wingless, later instars develop wing pads. Adult: Adults may be long-winged (macropterous, capable of migration) or short-winged (brachypterous, flightless); they continue feeding and reproducing. Total cycle: 20–30 days.",
        "cultural": "• Planting resistant rice varieties.\n• Implementing Alternate Wetting and Drying (AWD) to deny them a continuous humid environment at the stem base.\n• Avoiding excessive nitrogen fertilizer which causes dense, humid canopies.",
        "bio_controls": "• Strictly conserving spiders, mirid bugs, and aquatic beetles which are highly effective natural hunters of hoppers.",
        "chemical": "• Using selective insecticides (e.g., Buprofezin). Crucial warning: Avoid broad-spectrum chemicals that kill spiders, as this directly causes hopper resurgence."
    },
    "cicadellidae": {
        "name": "Leafhoppers (Ngusong kabayo - Green)",
        "general_desc": "Leafhoppers, especially the Green Leafhopper (Nephotettix virescens), are small but highly consequential pests in rice production. While they do feed directly on plant sap by piercing leaf tissue, their most devastating impact is as the primary vector of Rice Tungro Disease, the most destructive viral disease of rice in tropical Asia. Infected plants show characteristic yellow-orange discoloration, stunted growth, and reduced tillering. The virus is acquired rapidly by a leafhopper after feeding on an infected plant for just a few minutes, and can then be transmitted to a healthy plant almost immediately. Even low leafhopper populations can cause serious yield loss if Tungro virus is present in the area. Early-season monitoring of leafhopper activity is therefore critical for disease prevention.",
        "lifecycle": "Egg (leaf tissue): Females insert eggs singly into leaf tissue, typically along the midrib; eggs hatch in 6–9 days; females can transmit Tungro virus to the plant while laying. Nymph: Nymphs pass through 5 instars over 12–17 days; they are capable of acquiring and transmitting Tungro virus even in the earliest instars; nymphs feed actively on leaf sap. Adult: Adults are mobile and highly efficient vectors; a single adult can transmit Tungro to a healthy plant after just minutes of feeding; adults live 15–30 days. Total cycle: ~25 days.",
        "cultural": "• Synchronous planting to prevent continuous food supply across seasons.\n• Crop rotation with non-host plants (like legumes) during the dry season.\n• Destroying weed hosts surrounding the field.",
        "bio_controls": "• Encouraging natural predators like hunting spiders and tiny egg parasitoids.\n• Promoting healthy frog populations in the paddies.",
        "chemical": "• Applying seed treatments before planting.\n• Spraying recommended insecticides only if Tungro virus symptoms are detected alongside the hoppers."
    },
    "hesperiidae": {
        "name": "Skippers (Paruparo / Kinikiling)",
        "general_desc": "Skippers (family Hesperiidae) in the context of rice pests are commonly referred to as rice leaf folders. The adult is a small, fast-flying butterfly, but it is the larval stage that causes crop damage. After hatching, the larva spins silk threads to fold or roll a single rice leaf lengthwise, creating a protective tube in which it lives and feeds by scraping the green tissue from the inner surface, leaving behind white, papery streaks. Heavy infestations produce fields with many white, rolled leaves, signaling significant loss of photosynthetic area. The pest is favored by dense planting and high nitrogen fertilizer application, which produce lush, succulent foliage. While individual larvae cause limited damage, large populations during the tillering stage can reduce the leaf area index enough to affect yield.",
        "lifecycle": "Egg: Females lay single eggs on the upper or lower surface of rice leaves; eggs hatch in 4–6 days. Larva (leaf-folder): Newly hatched larvae immediately spin silk threads to fold a leaf into a protective tube, feeding on the green tissue from inside; they pass through 5–6 instars over 15–20 days, creating characteristic white, papery streaks and rolled leaves. Pupa: Pupation occurs inside the folded leaf or in the soil; the pupal stage lasts 7–10 days. Adult Butterfly: Adults are fast-flying skippers that feed on nectar and lay eggs back on rice leaves. Total cycle: ~30 days.",
        "cultural": "• Reducing dense planting and lowering nitrogen fertilizer use to prevent overly succulent leaves.\n• Manual removal and crushing of the folded leaves.",
        "bio_controls": "• Relying heavily on natural predators; skipper populations are usually kept naturally low by spiders, predatory crickets, and parasitic wasps.",
        "chemical": "• Chemical control is rarely recommended or necessary for skippers, as they rarely cause enough defoliation to impact yield."
    },
    "ampullariidae": {
        "name": "Golden Apple Snail (Kuhol)",
        "general_desc": "The Golden Apple Snail (Pomacea canaliculata), locally known as kuhol, is an introduced invasive species from South America that has become one of the most destructive pests in Philippine rice paddies. It feeds voraciously on young rice seedlings and transplants at and below the waterline, often clipping them entirely at the base within days of flooding. A single snail can destroy multiple seedlings per night. The pest is easily identified by its bright pink to orange egg clusters, which are laid in masses above the waterline on stalks, canal walls, and other structures. The eggs hatch within 1–2 weeks, releasing hundreds of juvenile snails into the field. The Golden Apple Snail thrives in flooded conditions and spread rapidly through irrigation canals. Its introduction into Philippine agriculture in the 1980s has caused billions of pesos in annual crop losses.",
        "lifecycle": "Egg: Females lay bright pink-to-orange egg masses (100–500 eggs per clutch) above the waterline on plant stalks, canal walls, and other structures; eggs hatch in 7–14 days and fall into the water. Juvenile: Hatchlings drop into the water and immediately begin feeding on algae and then soft plant tissue; juveniles grow rapidly and reach reproductive maturity in 2–3 months. Adult Snail: Adults can live for over a year, continuously laying egg masses every 1–2 weeks; they can survive dry conditions by burrowing into the soil and sealing their shells (estivation). Total cycle: 60–90 days to maturity.",
        "cultural": "• Handpicking adult snails and actively crushing the pink egg masses on stalks.\n• Constructing small, deep canals along the field edges to herd snails for easy mass collection.\n• Managing water levels (keeping it shallow during seedling stages).",
        "bio_controls": "• Releasing ducks into the paddies during fallow periods or before transplanting so they can eat juvenile snails.",
        "chemical": "• Applying approved molluscicides (e.g., Niclosamide) to localized canal areas, specifically immediately after transplanting when seedlings are most vulnerable."
    },
    "pentatomidae": {
        "name": "Rice Black Bug (Itim na atangya)",
        "general_desc": "The Rice Black Bug (Scotinophara coarctata) is a shiny, dark-colored true bug (Hemiptera) that is a significant pest in irrigated and rainfed lowland rice in Southeast Asia, including the Philippines. Both nymphs and adults feed by inserting their stylet mouthparts into the leaf sheaths at the base of tillers to extract sap, weakening the plant. The most severe symptom of infestation is “bugburn,” characterized by yellowing and deadening of tillers at the stem base that can resemble drought stress. Feeding at the booting and heading stages can result in sterile panicles and empty grains. Rice black bugs are nocturnal, hiding at the base of plants during the day and aggregating at field margins near weedy vegetation. They are migratory, attracted to lights during the full moon, and tend to multiply rapidly in areas with reduced natural enemy populations.",
        "lifecycle": "Egg: Females lay rows of 14–30 eggs arranged in a neat line on rice leaves; eggs hatch in 5–7 days and are light-colored before darkening. Nymph: Nymphs pass through 5 instars over 30–45 days; early instars are light brown and aggregate in groups; later instars darken progressively toward the adult black coloration; all instars feed on sap at the base of tillers. Adult: Shiny black adults are nocturnal, hiding at the base of plants during the day; they are migratory and attracted to bright lights during the full moon. Total cycle: 45–60 days.",
        "cultural": "• Setting up intense high-wattage light traps during the week of the full moon to catch migrating adults.\n• Temporarily raising paddy water levels to drown eggs and nymphs at the base.",
        "bio_controls": "• Mass application of Metarhizium anisopliae (a green muscardine fungus) which naturally infects and kills the bugs.",
        "chemical": "• Spraying synthetic pyrethroids, but strictly as a last resort if populations explode during the highly vulnerable booting stage of the crop."
    },
    "pyrgomorphidae": {
        "name": "Slant-faced Grasshopper (Tipaklong)",
        "general_desc": "Slant-faced grasshoppers (Atractomorpha spp. and related species) are large, elongated orthopterans that get their name from their distinctively angled facial profile. In rice fields, they are considered occasional rather than primary pests, typically feeding along the margins of fields or in areas adjacent to grass-covered embankments (dikes). Both nymphs and adults consume rice leaves by chewing from the edges inward, leaving ragged, notched margins. Their coloration—ranging from green to brown—provides exceptional camouflage among rice foliage, making detection difficult. Damage tends to be concentrated at field borders and rarely reaches yield-threatening levels across an entire paddock unless large aggregations appear. They are most active in the early morning and late afternoon, and their egg pods are buried in the soil near field margins.",
        "lifecycle": "Egg (soil pods): Females deposit egg pods containing 30–60 eggs into the soil near field margins; the eggs are protected by a frothy secretion that hardens; incubation takes 2–4 weeks depending on soil temperature. Nymph: Nymphs closely resemble adults but are smaller and wingless; they pass through 5–6 instars over 30–40 days, feeding on rice leaves from the margins inward; excellent camouflage makes detection difficult. Adult: Winged adults are more mobile and may migrate short distances; they continue feeding on leaves and lay egg pods in nearby soil. Total cycle: 60–80 days.",
        "cultural": "• Sweeping nets to manually clear specific infested margins of the field.\n• Plowing and harrowing the soil to expose and destroy buried egg pods.",
        "bio_controls": "• Encouraging insectivorous birds in the surrounding environment.\n• Utilizing naturally occurring entomopathogenic fungi.",
        "chemical": "• Spot-spraying specific heavily infested borders rather than blanket-spraying the entire field, as these are rarely widespread primary pests."
    },
    "chrysomelidae": {
        "name": "Leaf Beetles (Salagubang / Hispa)",
        "general_desc": "Leaf beetles of the family Chrysomelidae that attack rice include the Rice Hispa (Dicladispa armigera), a small, spiny beetle with a distinctive dark blue-black color. Adult beetles damage rice by scraping the upper surface of leaves, leaving white, translucent streaks parallel to the leaf veins. The larvae are more damaging: they mine inside the leaf tissue between the upper and lower epidermis, creating irregular, whitish tunnels or blotches visible to the naked eye. Heavily infested leaves turn white and wither, resembling drought stress. The pest is more common in direct-seeded fields and during periods of water stress. Outbreaks are associated with dense stands and grassy weeds on field dikes that serve as alternate breeding hosts. While rarely causing total crop failure, severe infestations during the vegetative stage can significantly reduce photosynthetic capacity and overall yield.",
        "lifecycle": "Egg: Females lay eggs individually on the leaf surface or inside leaf tissue in small clusters; eggs hatch in 4–7 days. Larva (leaf miner): Newly hatched larvae immediately bore into the leaf and begin mining between the upper and lower epidermis, creating white, irregular tunnels or blotches; they pass through 3–4 instars over 10–15 days; adults also scrape the leaf surface, leaving white streaks. Pupa: Pupation occurs inside the mined leaf or in the soil near the plant; the pupal stage lasts 5–8 days. Adult Beetle: Dark blue-black spiny adults emerge, continue leaf scraping, and mate. Total cycle: 25–35 days.",
        "cultural": "• Clipping the top leaves of seedlings before transplanting (which removes laid eggs).\n• Slashing and managing grassy weeds around the dikes that serve as alternate hosts.",
        "bio_controls": "• Conserving tiny egg parasitoid wasps that specifically target beetle eggs.",
        "chemical": "• Using systemic granular insecticides applied to the soil if severe white streaking is observed across the majority of seedlings."
    },
    "acrididae": {
        "name": "Locusts / Grasshoppers (Balang)",
        "general_desc": "Locusts (Locusta migratoria and related species) are among the most feared agricultural pests in history due to their capacity for mass migration and catastrophic crop destruction. In the Philippines, the migratory locust and the oriental migratory locust are the primary species of concern. Under favorable conditions (warm temperatures and crowding), solitary locusts transform into the gregarious phase, changing in behavior, body color, and size. These gregarious individuals form swarms that can number in the billions, traveling long distances and consuming virtually all vegetation in their path. In rice fields, both the nymph (hopper) bands and adult swarms strip leaves, stems, and panicles rapidly. Locusts are distinct from common grasshoppers in their ability to undergo this phase change. Hopper control during the nymph stage, before wings develop, is the most effective strategy for preventing a full-scale swarm.",
        "lifecycle": "Egg (soil): Females lay egg pods of 30–100 eggs into the soil in dry, open areas; eggs can remain dormant for extended periods during unfavorable conditions; incubation lasts 2–4 weeks. Nymph (Hopper): Wingless nymphs (called \"hoppers\") emerge and immediately aggregate in large bands; they pass through 5–6 instars over 30–40 days; hopper bands are the most controllable stage, before wings develop. Adult: Fully winged adults are capable of long-distance flight; under crowding and warmth, solitary adults transform into the gregarious phase—changing color, behavior, and forming destructive swarms. Total cycle: 50–70 days.",
        "cultural": "• Tilling the soil to desiccate buried egg pods.\n• Hand-catching or netting nymphs before they develop wings and mobility.",
        "bio_controls": "• Spraying biological control agents like Metarhizium acridum, a fungus highly specific to locusts and grasshoppers.",
        "chemical": "• Applying approved contact insecticides specifically targeting the concentrated hopper (nymph) stage before they mature and swarm."
    },
    "coreidae": {
        "name": "Horned Coreid Bugs (Atangya)",
        "general_desc": "Rice bugs, particularly Leptocorisa oratorius and Leptocorisa acuta (family Alydidae), are significant pests during the reproductive stage of rice. Though commonly grouped under the broader “coreid bug” label, they are correctly classified under Alydidae (broad-headed bugs). Both adults and nymphs are equipped with needle-like piercing-sucking mouthparts that they insert into developing rice grains from the pre-flowering to soft dough stage, extracting the liquid grain contents. Agricultural impact is severe and wide-ranging: feeding causes grains to become empty, chalky, partially formed, or discolored (known as “pecky” rice), directly reducing yield quantity and milling recovery quality. Their feeding punctures also serve as entry points for fungal and bacterial grain pathogens. Rice attacked by these bugs is reported to have an unpleasant odor even after cooking. In the Philippines, rice bug infestations have been estimated to cause 10–40% crop losses. The bugs are typically found in grassy areas at field margins during the vegetative stage, migrating into the paddy once panicles emerge and grain-filling begins. When disturbed, they emit a strong, foul-smelling defensive secretion. Population explosions are commonly linked to staggered planting schedules across a landscape, which provide a continuous supply of grain-filling crops, as well as the presence of extensive grassy weed areas near canals and field borders that serve as off-season breeding habitats.",
        "lifecycle": "Egg (rows): Females lay neat double rows of 10–20 shiny, dark eggs on rice leaves, usually on the upper surface; eggs hatch in 5–8 days; newly laid eggs are green, darkening before hatching. Nymph: Nymphs pass through 5 instars over 20–30 days; early instars are brightly colored and aggregate in groups; all instars are equipped with piercing mouthparts and feed on developing grain from the earliest stages; they emit a foul defensive odor when disturbed. Adult: Adults are slender, green to brownish bugs; they are highly mobile, migrating from field margins into paddies as panicles emerge; adults live 20–30 days and continue feeding and mating. Total cycle: 35–45 days.",
        "cultural": "• Removing grassy weeds from field borders where they hide.\n• Harvesting the crop at the optimal time to prevent late-stage feeding damage.\n• Using attractant traps (like rotting snail meat or specific baits) to draw them away from grains.",
        "bio_controls": "• Conserving parasitic wasps (like Gryon species) that specifically lay their own eggs inside the coreid bug's eggs.",
        "chemical": "• Spraying synthetic insecticides only if field sampling shows a high population actively piercing the developing milky grains."
    }
}

tl_data = {
    "crambidae": {
        "name": "Stem Borers / Moths (Aksip / Kuwong)",
        "general_desc": "Ang stem borers ay kabilang sa pinaka-mapaminsalang mga peste sa pagsasaka ng palay sa Pilipinas. Naglalagay ang mga gamu-gamong adult ng mga itlog sa mga dahon ng palay, at kapag napisa na, ang mga uod ay bumubutas diretso sa tangkay. Sa mga batang halaman, pinapatay nito ang gitnang usbong—isang kondisyon na tinatawag na “deadheart,” kung saan nanilaw ang dahon at madaling mahila. Sa mga hinog na halaman naman, ang pagkain ng uod sa base ng tangkay ay pumipigil sa pagdaloy ng sustansya sa mga butil, na nagdudulot ng mapuputing, walang lamang mga uhay na tinatawag na “whitehead.” Maraming uri ang umaatake sa palay, kabilang ang striped stem borer (Chilo suppressalis) at yellow stem borer (Scirpophaga incertulas). Pinakamasama ang pag-atake sa maagang yugto ng paglaki at sa panahon ng pamumunga. Maaaring maabot ang 30–50% na pagkawala ng ani kung hindi maagapan.",
        "lifecycle": "Itlog: Inilalagay ng babae sa mga dahon ng palay bilang mga kumpol na nakasaklaw ng ~100 itlog; nagpipisa sa loob ng 5–7 araw. Uod (sa loob ng tangkay): Ang bagong pisang uod ay bumubutas sa base ng tangkay at kumakain mula sa loob; may 5–6 na yugto ng pagbabago; tumatagal ng 20–30 araw. Pupa (sa loob ng tangkay): Nagsasanla sa loob ng patay na tangkay; tumatagal ng 7–10 araw. Gamu-gamo: Ang adult ay lumabas, nabubuhay ng 5–7 araw lamang, at naghahanap agad ng kapareha. Kabuuang ikot: 30–40 araw.",
        "cultural": "• Sabayang pagtatanim sa buong komunidad upang masira ang ikot ng peste.\n• Pag-aani malapit sa lupa upang alisin ang mga nag-iistay na pupa.\n• Pag-aararo at pagbabaha ng palayan kaagad pagkatapos ng anihan.",
        "bio_controls": "• Pangangalaga at pagpapakawala ng mga parasitikong putakti (hal., Trichogramma) na sumisira sa mga itlog ng peste.\n• Pagprotekta sa mga natural na kalaban tulad ng mga gagamba at salagubang sa lupa.",
        "chemical": "• Paggamit ng systemic insecticides (hal., Cartap hydrochloride) kung ang pinsala ng \"deadheart\" ay lumagpas sa 10% na economic threshold sa vegetative stage."
    },
    "noctuidae": {
        "name": "Armyworms (Uod militar / Harabas)",
        "general_desc": "Ang armyworms (Mythimna separata at mga kaugnay na uri) ay lubhang mapaminsalang mga uod sa pamilyang Noctuidae na kilala sa kanilang maramihang pagkain. Ang pangalan nila ay nagmula sa kanilang gawi ng paglipat sa malalaking grupo sa mga palayan kapag kulang ang pagkain—tulad ng mga hukbong nagmamartsa. Ang mga bagong pisang uod ay kumakain sa mga gilid ng dahon, ngunit ang mga mas matatanda (lalo na ang ika-5 at ika-6 na instar) ay umuubos ng buong mga dahon at maging ng uhay. Kadalasan silang kumakain sa gabi at nagtatago sa lupa sa araw, kaya mahirap silang matuklas. Sa Pilipinas, sila ay seryosong banta sa panahon ng tag-ulan. Ang matinding pag-atake ay maaaring makalbo ng buong palayan sa loob ng ilang araw.",
        "lifecycle": "Itlog: Inilalagay sa mga dahon bilang mga kumpol na may 100–300 itlog; nagpipisa sa loob ng 4–6 araw. Uod (6 na yugto): Ang mga batang uod ay kumakain sa mga gilid ng dahon; ang mas matatandang instar (lalo na ang ika-5 at ika-6) ay lubos na kumakain sa gabi at nagtatago sa lupa sa araw; tumatagal ng 14–21 araw. Pupa (sa lupa): Nagsasanla sa ilalim ng lupa sa loob ng 8–10 araw. Gamu-gamo: Ang adult ay lumalabas, kumakain ng pulot-pukyutan, at mabilis na nagpaparami. Kabuuang ikot: ~30 araw.",
        "cultural": "• Pagbabaha ng punlaan upang malunod ang mga uod.\n• Malalim na pag-aararo ng palayan pagkatapos ng anihan upang mailantad ang mga pupa sa init ng araw.\n• Paghukay ng mga kanal sa paligid ng hindi pa nahawaang palayan upang mapigilan ang mga uod na lumipat.",
        "bio_controls": "• Paggamit ng natural na nagaganap na Nucleopolyhedrovirus (NPV) na espesipikong nag-iimpeksyon sa mga uod ng armyworm.\n• Pagpapalakas ng populasyon ng mga mandaragit na ibon at natural na putakti.",
        "chemical": "• Pagwisik ng foliar insecticides (tulad ng synthetic pyrethroids) sa hapon kapag aktibo ang mga uod, ngunit sa malalang outbreak lamang."
    },
    "delphacidae": {
        "name": "Planthoppers (Ngusong kabayo - Brown)",
        "general_desc": "Ang planthoppers, lalo na ang Brown Planthopper (Nilaparvata lugens), ay isa sa mga pinaka-mapanganib na insektong peste ng palay sa Asya. Ang parehong nymph at adult ay kumakain sa pamamagitan ng pagpasok ng kanilang matutulis na bibig sa phloem na bahagi ng tangkay upang sumipsip ng katas. Ang matinding pagkain ay nagdudulot ng “hopperburn,” isang kondisyon kung saan biglang nangangalumata at natutuyo ang mga apektadong bahagi ng palayan. Bukod sa direktang pinsala, ang mga planthopper ay nagsisilding tagapagdala ng Grassy Stunt at Ragged Stunt virus, na maaaring puminsala sa buong pananim. Mabilis silang nagpaparami sa mainit, mahalumigmig, at nitrogen-rich na kapaligiran. Sa Pilipinas, sila ay pangunahing dahilan ng malawak na pagkawala ng ani.",
        "lifecycle": "Itlog (sa tangkay ng dahon): Ang babae ay naglalagay ng mga itlog sa loob ng tissue ng tangkay ng dahon sa isang hilera; nagpipisa sa loob ng 7–10 araw. Nymph (5 yugto): Ang mga bagong pisang nymph ay mabilis at aktibo; sila ay sumisipsip na ng katas ng halaman mula sa pagpisa pa lamang; ang bawat yugto ay tumatagal ng 2–4 araw, na kabuuang 15–20 araw. Adult: Maaaring may pakpak (macropterous) o walang pakpak (brachypterous); patuloy na sumisipsip at nagpaparami. Kabuuang ikot: 20–30 araw.",
        "cultural": "• Pagtatanim ng mga barayti ng palay na lumalaban sa mga planthopper.\n• Paggamit ng Alternate Wetting and Drying (AWD) upang maiwasan ang patuloy na mahalumigmig na kapaligiran sa base ng tangkay.\n• Pag-iwas sa labis na paggamit ng nitrogen na pampataba na nagdudulot ng siksik at mahalumigmig na palayan.",
        "bio_controls": "• Mahigpit na pangangalaga ng mga gagamba, mirid bug, at aquatic beetle na epektibong natural na mangangaso ng mga planthopper.",
        "chemical": "• Paggamit ng selective insecticides (hal., Buprofezin). Mahalagang babala: Iwasan ang broad-spectrum na kemikal na pumapatay sa mga gagamba, dahil ito ay direktang nagdudulot ng hopper resurgence."
    },
    "cicadellidae": {
        "name": "Leafhoppers (Ngusong kabayo - Green)",
        "general_desc": "Ang leafhoppers, lalo na ang Green Leafhopper (Nephotettix virescens), ay maliliit ngunit lubhang mapanganib na mga peste sa pagsasaka ng palay. Habang sila ay direktang kumakain sa katas ng halaman sa pamamagitan ng pagtubok ng dahon, ang kanilang pinaka-mapaminsalang epekto ay bilang pangunahing tagapagdala ng Rice Tungro Disease—ang pinakamasamang viral na sakit ng palay sa tropikal na Asya. Ang mga nahawaang halaman ay nagpapakita ng katangiang dilaw-kahel na kulay, inatsang paglaki, at nabawasang mga supling. Ang virus ay mabilis na natatanggap ng leafhopper pagkatapos magsipsip sa isang nahawaang halaman sa loob lamang ng ilang minuto, at maaari na itong maipasa kaagad sa isang malusog na halaman. Kahit maliit na populasyon ng leafhopper ay maaaring magdulot ng malubhang pagkawala ng ani kung may Tungro virus sa lugar.",
        "lifecycle": "Itlog (sa laman ng dahon): Ang babae ay nagtatago ng mga itlog sa loob ng tissue ng dahon, karaniwang malapit sa midrib; nagpipisa sa loob ng 6–9 araw. Nymph: May 5 yugto ng pag-unlad; ang mga nymph ay kumakain na at kayang maipasa ang Tungro virus mula sa una pang yugto; tumatagal ng 12–17 araw. Adult: Ang adult ay kumakain, nagpaparami, at nagtataglay ng virus; nabubuhay ng 15–30 araw. Kabuuang ikot: ~25 araw.",
        "cultural": "• Sabayang pagtatanim upang maiwasan ang patuloy na pagkain sa iba’t ibang panahon.\n• Crop rotation gamit ang mga halaman na hindi tinatangkilik ng leafhopper (tulad ng mga legumes) sa tuyong panahon.\n• Pagsisira ng mga damong nagsisilbing tirahan ng leafhopper sa paligid ng palayan.",
        "bio_controls": "• Pagpapalakas ng mga natural na kalaban tulad ng mga manghuhulas na gagamba at maliliit na egg parasitoid.\n• Pagtataguyod ng malusog na populasyon ng mga palaka sa mga palayan.",
        "chemical": "• Paggamit ng seed treatment bago magtanim.\n• Pagwisik ng inirerekomendang insecticide kung may nakitang sintomas ng Tungro virus kasabay ng mga leafhopper."
    },
    "hesperiidae": {
        "name": "Skippers (Paruparo / Kinikiling)",
        "general_desc": "Ang skippers (pamilyang Hesperiidae) sa konteksto ng mga peste ng palay ay karaniwang tinatawag na rice leaf folders. Ang adult ay isang maliit, mabilis na lumilipad na paruparo, ngunit ang yugto ng uod ang nagdudulot ng pinsala sa pananim. Pagkatapos mapisa, ang uod ay gumagamit ng sinulid na sutla upang tiklupan o igulong ang isang dahon ng palay nang pahaba, na gumagawa ng isang protektibong tubo kung saan ito nakatira at kumakain sa pamamagitan ng pagkaskas ng berdeng bahagi mula sa loob, na nag-iiwan ng puting, parang-papel na mga guhit. Ang matinding pag-atake ay nagdudulot ng maraming puting, nakatiklop na dahon sa palayan. Ang peste ay mas karaniwan sa siksik na pagtatanim at mataas na paggamit ng nitrogen na fertilizer.",
        "lifecycle": "Itlog: Inilalagay ng isa-isa sa mga dahon ng palay; nagpipisa sa loob ng 4–6 araw. Uod (leaf-folder): Ang bagong pisang uod ay agad na gumagawa ng silk tube sa pamamagitan ng pagtitiklop ng dahon; kumakain sa loob ng nakatiklop na dahon; may 5–6 na yugto na tumatagal ng 15–20 araw. Pupa: Nagsasanla sa loob ng nakatiklop na dahon o sa lupa; tumatagal ng 7–10 araw. Paruparo: Ang adult ay lumalabas, naghanap ng kapareha, at naglalagay ng mga itlog sa mga dahon ng palay. Kabuuang ikot: ~30 araw.",
        "cultural": "• Pagbawas ng siksik na pagtatanim at pagbaba ng paggamit ng nitrogen na pampataba upang maiwasan ang sobrang malambot na dahon.\n• Mano-manong pag-aalis at pag-dupak sa mga nakatiklop na dahon.",
        "bio_controls": "• Lubos na pag-asa sa mga natural na kalaban; ang mga populasyon ng skipper ay karaniwang natural na kontrolado ng mga gagamba, mandaragit na kuliglig, at parasitikong putakti.",
        "chemical": "• Ang chemical control ay bihira at karaniwang hindi kailangan para sa mga skipper, dahil bihira silang magdulot ng sapat na defoliation upang makaapekto sa ani."
    },
    "ampullariidae": {
        "name": "Golden Apple Snail (Kuhol)",
        "general_desc": "Ang Golden Apple Snail (Pomacea canaliculata), na kilala sa lokal bilang kuhol, ay isang invasive na uri mula sa Timog Amerika na naging isa sa pinaka-mapaminsalang peste sa mga palayan ng Pilipinas. Lubos itong kumakain sa mga batang punla at transplant ng palay sa loob at sa ilalim ng tubig, madalas na tinatanggal ang mga ito sa punla sa loob ng ilang araw pagkatapos ng pagbabaha. Isang kuhol lang ay maaaring sumira ng maraming punla sa isang gabi. Ang peste ay madaling makilala sa pamamagitan ng maliwanag na pula hanggang kahel na mga kumpol ng itlog, na inilalagay sa mga tangkay, gilid ng kanal, at iba pang istraktura. Ang mga itlog ay nagpipisa sa loob ng 1–2 linggo, na naglalabas ng daan-daang mga batang kuhol sa palayan. Ang pagpapakilala nito sa pagsasakang Pilipino noong 1980s ay nagdulot ng bilyun-bilyong pisong pagkawala sa taon-taon.",
        "lifecycle": "Itlog: Inilalagay ng babae sa mga tangkay, dingding ng kanal, at iba pang mga istraktura na nasa itaas ng linya ng tubig bilang maliwanag na pula hanggang rosas na mga kumpol (100–500 itlog bawat kumpol); nagpipisa sa loob ng 7–14 araw. Batang kuhol (Juvenile): Ang mga batang kuhol ay bumabagsak sa tubig pagkatapos mapisa; kaagad na nagsisimulang kumain ng mga algae at mga batang halaman; mabilis na lumalaki sa loob ng 2–3 buwan. Adult: Ang mga adult ay maaaring mabuhay ng mahigit isang taon at patuloy na nagpaparami; maaaring mag-estivate sa tuyong panahon sa ilalim ng lupa.",
        "cultural": "• Mano-manong pamumulot ng mga adult na kuhol at aktibong pagdurog ng mga rosas na kumpol ng itlog sa mga tangkay.\n• Paggawa ng maliliit at malalim na kanal sa mga gilid ng palayan upang tipunin ang mga kuhol para sa madaling koleksyon.\n• Pamamahala ng antas ng tubig (pagtitiyak na mababaw ang tubig sa panahon ng mga batang punla).",
        "bio_controls": "• Pagpapakawala ng mga pato sa mga palayan sa panahon ng paghinto ng pagtatanim o bago magtanim upang makain nila ang mga batang kuhol.",
        "chemical": "• Paggamit ng aprubadong molluscicide (hal., Niclosamide) sa mga kanal lamang, lalo na kaagad pagkatapos ng pagtatanim kapag pinaka-vulnerable ang mga punla."
    },
    "pentatomidae": {
        "name": "Rice Black Bug (Itim na atangya)",
        "general_desc": "Ang Rice Black Bug (Scotinophara coarctata) ay isang makintab, maitim na kulay na tunay na bug (Hemiptera) na isang makabuluhang peste sa mga palayan ng Pilipinas at Timog-silangang Asya. Ang parehong nymph at adult ay kumakain sa pamamagitan ng pagpasok ng kanilang mga bibig sa mga dahon ng puno upang sumipsip ng katas, na nagpapahina sa halaman. Ang pinakamatinding sintomas ng pag-atake ay ang “bugburn,” na nailalarawan sa pamamagitan ng paninilaw at pagkamatay ng mga supling sa base ng tangkay. Ang pagkain sa panahon ng pamumunga ay maaaring magresulta sa mga sterile na uhay at walang lamang mga butil. Ang mga rice black bug ay gabi-gabi ang gawi, nagtatago sa base ng mga halaman sa araw at nagtitipon sa mga gilid ng palayan malapit sa mga masamang damo. Sila ay migratoryo at naaakit sa liwanag sa panahon ng buwan.",
        "lifecycle": "Itlog: Inilalagay sa mga dahon ng palay bilang mga kumpol na may 14–30 itlog sa isang hilera; nagpipisa sa loob ng 5–7 araw. Nymph: May 5 yugto ng pag-unlad; ang mga bagong pisang nymph ay maliwanag ang kulay at unti-unting nagdidilim habang sila ay lumalaki; kumakain na sa base ng tangkay mula sa unang yugto; tumatagal ng 30–45 araw. Adult: Ang adult ay maitim at makintab; nabubuhay ng ilang buwan; migratoryo at naaakit sa liwanag sa buwan. Kabuuang ikot: 45–60 araw.",
        "cultural": "• Paglalagay ng mga malakas na light trap sa panahon ng buwan upang mahuli ang mga lumalipat na adult.\n• Pansamantalang pagpapalaki ng antas ng tubig sa palayan upang malunod ang mga itlog at nymph sa base ng halaman.",
        "bio_controls": "• Malawakang paggamit ng Metarhizium anisopliae (isang berdeng muscardine fungus) na natural na nag-iimpeksyon at pumapatay sa mga bug.",
        "chemical": "• Pagwisik ng synthetic pyrethroids, ngunit bilang huling paraan lamang kung ang populasyon ay sumabog sa kritikal na booting stage ng pananim."
    },
    "pyrgomorphidae": {
        "name": "Slant-faced Grasshopper (Tipaklong)",
        "general_desc": "Ang slant-faced grasshoppers (Atractomorpha spp. at mga kaugnay na uri) ay malalaki, mahabang orthoptera na nagmula ang pangalan sa kanilang katangi-tanging anggular na mukha. Sa mga palayan, sila ay itinuturing na paminsan-minsang peste kaysa pangunahing peste, karaniwan silang kumakain sa mga gilid ng palayan o sa mga lugar malapit sa mga pinaluarang pilapil na may damo. Ang parehong nymph at adult ay kumakain ng mga dahon ng palay sa pamamagitan ng pagngata mula sa mga gilid papasok, na nag-iiwan ng mga jagged, notched na mga gilid. Ang kanilang kulay—mula berde hanggang kayumanggi—ay nagbibigay ng kahanga-hangang camouflage sa mga dahon ng palay. Ang pinsala ay karaniwang naka-konsentra sa mga gilid ng palayan at bihirang umabot sa mga antas na nagbabanta sa ani sa buong palayan maliban kung may malalaking grupo.",
        "lifecycle": "Itlog (sa lupa): Ang babae ay naglalagay ng mga egg pod sa loob ng lupa malapit sa mga gilid ng palayan; ang bawat pod ay may 30–60 itlog; nagpipisa pagkatapos ng 2–4 na linggo depende sa temperatura. Nymph: Ang mga batang grasshopper ay kamukhang-kamukha ng adult ngunit mas maliit at walang pakpak; may 5–6 na yugto ng pag-unlad; kumakain na ng mga dahon mula sa simula; tumatagal ng 30–40 araw. Adult: Ang adult na may pakpak ay mas mobile at kumakain pa rin ng mga dahon; nabubuhay ng ilang buwan at maaaring mag-migrate. Kabuuang ikot: ~60–80 araw.",
        "cultural": "• Paggamit ng mga lambat upang mano-manong linisin ang mga nahawaang gilid ng palayan.\n• Pag-aararo at pag-haharrow ng lupa upang mailantad at masira ang mga nakatago na egg pod.",
        "bio_controls": "• Pagpapalakas ng mga insektiborous na ibon sa kapaligiran.\n• Paggamit ng natural na nagaganap na entomopathogenic fungi.",
        "chemical": "• Spot-spray sa mga partikular na nahawaang gilid ng palayan kaysa sa buong palayan, dahil bihirang kumalat ang mga ito sa malawak na lugar."
    },
    "chrysomelidae": {
        "name": "Leaf Beetles (Salagubang / Hispa)",
        "general_desc": "Ang mga leaf beetle ng pamilyang Chrysomelidae na umaatake sa palay ay kinabibilangan ng Rice Hispa (Dicladispa armigera), isang maliit, may tinik na beetle na may katangi-tanging maitim-asul na kulay. Ang mga adult na beetle ay nagdudulot ng pinsala sa palay sa pamamagitan ng pagkaskas sa itaas na ibabaw ng mga dahon, na nag-iiwan ng puting, transparent na mga guhit na parallel sa mga ugat ng dahon. Ang mga uod ay mas mapaminsala: nagmimina sila sa loob ng dahon sa pagitan ng itaas at ibabang epidermis, na gumagawa ng mga irregular na puting tunnel o batik na nakikita ng mata. Ang malubhang mga nahawaang dahon ay nangingitim at natutuyo, na kahawig ng stress sa tagtuyot. Ang peste ay mas karaniwan sa mga palayan na direktang binhi at sa panahon ng stress sa tubig.",
        "lifecycle": "Itlog: Inilalagay ng babae sa ibabaw ng mga dahon o tissue ng dahon sa maliit na grupo; nagpipisa sa loob ng 4–7 araw. Uod (leaf miner): Ang bagong pisang uod ay agad na bumubutas sa loob ng dahon at nagmimina sa pagitan ng itaas at ibabang epidermis; gumagawa ng mga puting tunnel o blotch; may 3–4 na yugto na tumatagal ng 10–15 araw. Pupa: Nagsasanla sa loob ng dahon o sa lupa malapit sa halaman; tumatagal ng 5–8 araw. Salagubang (Adult): Ang adult ay kumakaskas sa ibabaw ng dahon at naglalagay ng bagong mga itlog. Kabuuang ikot: ~25–35 araw.",
        "cultural": "• Pagputol ng dulo ng mga dahon ng punla bago magtanim (inaalis ang mga nalagay nang itlog).\n• Pagputol at pamamahala ng mga damong nasa paligid ng pilapil na nagsisilbing alternatibong tirahan.",
        "bio_controls": "• Pangangalaga ng maliliit na egg parasitoid na putakti na espesipikong nagtatarget sa mga itlog ng beetle.",
        "chemical": "• Paggamit ng systemic granular insecticide sa lupa kung matinding pagpuputi ng dahon ang makikita sa karamihan ng mga punla."
    },
    "acrididae": {
        "name": "Locusts / Grasshoppers (Balang)",
        "general_desc": "Ang mga locust (Locusta migratoria at mga kaugnay na uri) ay kabilang sa pinaka-kinakatakutang mga peste sa agrikultura sa kasaysayan dahil sa kanilang kakayahang magsagawa ng malawak na migrasyon at mapaminsalang pag-ubos ng pananim. Sa Pilipinas, ang migratory locust at oriental migratory locust ang mga pangunahing uri na nag-aalalalay. Sa ilalim ng mga pabor na kondisyon (mataas na temperatura at siksik na populasyon), ang mga nag-iisang locust ay nagbabago sa gregarious na phase, nagbabago sa ugali, kulay ng katawan, at sukat. Ang mga indibidwal na ito sa gregarious phase ay bumubuo ng mga kawan na maaaring umabot sa bilyun-bilyon, naglalakbay ng malalayong distansya at kinakain ang halos lahat ng halaman sa kanilang daanan. Sa mga palayan, ang parehong banda ng nymph (hopper) at mga kawan ng adult ay mabilis na nagtatanggal ng mga dahon, tangkay, at uhay.",
        "lifecycle": "Itlog (sa lupa): Ang babae ay naglalagay ng mga egg pod na may 30–100 itlog sa loob ng lupa sa mga lugar na tuyo; maaaring manatiling dorment ang mga itlog sa matagal na panahon. Nymph (Hopper): Ang mga bagong pisang nymph (tinatawag na “hoppers”) ay walang pakpak at mas madaling kontrolin; sila ay nagtitipon sa malalaking grupo at kumakain nang labis; may 5–6 na yugto na tumatagal ng 30–40 araw. Adult: Ang mga adult ay may ganap na pakpak at kayang lumipad nang malalayong distansya; kapag nasa gregarious phase, bumubuo sila ng malalaking kawan. Kabuuang ikot: ~50–70 araw.",
        "cultural": "• Pagbubungkal ng lupa upang matuyo ang mga nakatago na egg pod.\n• Mano-manong paghuli o paglalagay ng lambat sa mga nymph bago pa sila magkaroon ng pakpak.",
        "bio_controls": "• Pagwisik ng mga biological control agent tulad ng Metarhizium acridum, isang fungi na espesipikong nakakaakit sa mga locust at grasshopper.",
        "chemical": "• Paggamit ng aprubadong contact insecticide na espesipikong nagtatarget sa nakakonsentradong hopper (nymph) stage bago pa sila lumago at maging kawan."
    },
    "coreidae": {
        "name": "Horned Coreid Bugs (Atangya)",
        "general_desc": "Ang mga rice bug, lalo na ang Leptocorisa oratorius at Leptocorisa acuta (pamilyang Alydidae), ay makabuluhang mga peste sa panahon ng pagpaparami ng palay. Bagaman karaniwang iniuuri sa mas malawak na “coreid bug” na kategorya, ang mga ito ay wastong inuuri sa ilalim ng Alydidae (broad-headed bugs). Ang parehong adult at nymph ay may matutulis na bibig na kanilang ipinasok sa mga nagbubuo pang butil ng palay mula sa pre-flowering hanggang soft dough stage, sinisipsip ang likidong nilalaman. Ang epekto sa agrikultura ay malubha: ang pagkain ay nagdudulot ng mga butil na maging walang laman, malabo, bahagyang nabuo, o may kulay (kilala bilang “pecky” na bigas), na direktang nagbabawas ng dami at kalidad ng ani. Ang mga butas ng kanilang pagkain ay nagsisilding mga pasukan din para sa mga pathogen na fungal at bacterial sa butil. Ang bigas na inaatake ng mga bug na ito ay iniulat na may hindi masarap na amoy kahit pagkatapos maluto. Sa Pilipinas, ang pag-atake ng rice bug ay tinatayang nagdudulot ng 10–40% na pagkawala ng ani.",
        "lifecycle": "Itlog: Inilalagay sa mga dahon ng palay bilang mga hilera na may 10–20 itlog sa bawat kumpol; nagpipisa sa loob ng 5–8 araw. Nymph: May 5 yugto ng pag-unlad; ang mga bagong pisang nymph ay may matingkad na kulay at nagsasama-sama; sila ay kumakain na sa mga butil ng palay mula sa unang yugto; tumatagal ng 20–30 araw. Adult: Ang adult ay mas malaki at mas mobile; kumakain ng mga butil ng palay sa milky at dough stage; naglalabas ng matapang na amoy kapag nagambala; nabubuhay ng 20–30 araw. Kabuuang ikot: ~35–45 araw.",
        "cultural": "• Pag-aalis ng mga damong nasa mga gilid ng palayan kung saan sila nagtatago.\n• Pag-aani ng pananim sa tamang oras upang maiwasan ang pagkain sa huling yugto.\n• Paggamit ng mga bitag na pangakit (tulad ng bulok na karne ng kuhol o espesyal na pampakit) upang mailayo sila sa mga butil.",
        "bio_controls": "• Pagwisik ng synthetic insecticide kung ang field sampling ay nagpapakita ng mataas na populasyon na aktibong tumutusok sa mga nagbubuo pang milky grain.",
        "chemical": "• Pagwisik ng synthetic insecticide kung ang field sampling ay nagpapakita ng mataas na populasyon na aktibong tumutusok sa mga nagbubuo pang milky grain."
    }
}

# The bio_controls for coreidae Tagalog has a bit of difference, let me check the original text.
# The original Tagalog text says:
# • Conserving parasitic wasps (like Gryon species) that specifically lay their own eggs inside the coreid bug's eggs. 
# wait, in Tagalog the original is:
# Parasitoid wasps
# Then chemical control: • Pagwisik ng synthetic insecticide kung ang field sampling ay nagpapakita ng mataas na populasyon na aktibong tumutusok sa mga nagbubuo pang milky grain.
tl_data["coreidae"]["bio_controls"] = "• Parasitoid wasps"

def generate_xml_blocks(data_dict):
    xml_lines = []
    for key, values in data_dict.items():
        xml_lines.append(f'    <!-- Pest Details - {key.capitalize()} -->')
        
        name = values["name"].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("'", "\\'")
        general = values["general_desc"].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("'", "\\'")
        lifecycle = values["lifecycle"].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("'", "\\'")
        bio = values["bio_controls"].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("'", "\\'")
        cultural = values["cultural"].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("'", "\\'")
        chemical = values["chemical"].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("'", "\\'")

        xml_lines.append(f'    <string name="{key}_name">{name}</string>')
        xml_lines.append(f'    <string name="{key}_general_desc">{general}</string>')
        xml_lines.append(f'    <string name="{key}_lifecycle">{lifecycle}</string>')
        xml_lines.append(f'    <string name="{key}_bio_controls">{bio}</string>')
        xml_lines.append(f'    <string name="{key}_cultural">{cultural}</string>')
        xml_lines.append(f'    <string name="{key}_chemical">{chemical}</string>')
        xml_lines.append('')
    return "\n".join(xml_lines)

en_xml = generate_xml_blocks(en_data)
tl_xml = generate_xml_blocks(tl_data)

import io

def replace_in_file(filepath, new_xml):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    start_idx = content.find('<!-- Pest Details - Crambidae -->')
    end_idx = content.find('</resources>')
    
    if start_idx != -1 and end_idx != -1:
        new_content = content[:start_idx] + new_xml + "\n" + content[end_idx:]
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print(f"Successfully replaced in {filepath}")
    else:
        print(f"Could not find replacement boundaries in {filepath}")

replace_in_file(r"C:\Users\Admin\StudioProjects\SPIM9\app\src\main\res\values\strings.xml", en_xml)
replace_in_file(r"C:\Users\Admin\StudioProjects\SPIM9\app\src\main\res\values-tl\strings.xml", tl_xml)
